name = "rw-owr"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "*"
GITHUB_REPO_OWNER = "your-github-username"
GITHUB_REPO_NAME = "your-repo-name"
GITHUB_BRANCH = "main"

[secrets]
GITHUB_TOKEN = "your-github-personal-access-token"
